name: Build and Release Smaller Tailscale

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest non-pre Tailscale tag
        id: get_tag
        run: |
          git clone https://github.com/tailscale/tailscale.git
          cd tailscale
          LATEST_TAG=$(git tag -l --sort=-v:refname | grep -v -E '(pre|rc)' | head -n 1)
          echo "::set-output name=latest_tag::$LATEST_TAG"

      - name: Check if tag already built
        id: check_tag
        run: |
          if git rev-parse ${{ steps.get_tag.outputs.latest_tag }} >/dev/null 2>&1; then
            echo "::set-output name=tag_exists::true"
          else
            echo "::set-output name=tag_exists::false"
          fi

      - name: Set up Go
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Install UPX
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Build smaller Tailscale binary
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          cd tailscale
          git checkout ${{ steps.get_tag.outputs.latest_tag }}
          ./build_dist.sh --extra-small
          mv dist/tailscale* ../tailscale.combined

      - name: Create non-compressed binary
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          cp tailscale.combined tailscale-small-${{ steps.get_tag.outputs.latest_tag }}

      - name: Compress with UPX
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          upx --lzma --best ./tailscale.combined
          mv tailscale.combined tailscale-small-upx-${{ steps.get_tag.outputs.latest_tag }}

      - name: Create Release
        if: steps.check_tag.outputs.tag_exists == 'false'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.latest_tag }}
          release_name: Tailscale ${{ steps.get_tag.outputs.latest_tag }}
          body: |
            This release contains two versions of the Tailscale binary:
            - `tailscale-small-${{ steps.get_tag.outputs.latest_tag }}`: Non-compressed version
            - `tailscale-small-upx-${{ steps.get_tag.outputs.latest_tag }}`: UPX-compressed version

            The UPX-compressed version is smaller but may trigger false positives in some security software.
          draft: false
          prerelease: false

      - name: Upload Non-Compressed Binary
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tailscale-small-${{ steps.get_tag.outputs.latest_tag }}
          asset_name: tailscale-small-${{ steps.get_tag.outputs.latest_tag }}
          asset_content_type: application/octet-stream

      - name: Upload UPX-Compressed Binary
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tailscale-small-upx-${{ steps.get_tag.outputs.latest_tag }}
          asset_name: tailscale-small-upx-${{ steps.get_tag.outputs.latest_tag }}
          asset_content_type: application/octet-stream
