name: Releases

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Linux
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: "386"
          - goos: linux
            goarch: loong64
          - goos: linux
            goarch: arm
            goarm: "5"
          - goos: linux
            goarch: arm
            goarm: "7"
          # mips
          - goos: linux
            goarch: mips
          - goos: linux
            goarch: mipsle
          - goos: linux
            goarch: mips64
          - goos: linux
            goarch: mips64le
          # macOS
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          # Windows
          # - goos: windows
          #   goarch: amd64
          # - goos: windows
          #   goarch: arm64
          # BSDs
          - goos: freebsd
            goarch: amd64
          - goos: openbsd
            goarch: amd64
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
    - uses: actions/checkout@v1
    - name: Get data
      id: data
      run: |
        echo "##[set-output name=version;]v$(grep tailscale_version= usr/bin/tailscaled | grep -oE '[[:digit:]]+.[[:digit:]]+.[[:digit:]]+')-$(git rev-parse --short HEAD)-autoupdate"
        echo "##[set-output name=commit;]$(git rev-parse HEAD)"
    - name: Generate tar archive
      run: ./generate-tar.sh ${{ steps.data.outputs.version }}
    - name: List
      run: ls -alh .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "openwrt-tailscale-enabler-*.tgz"
#         bodyFile: "body.md"
        commit: ${{ steps.data.outputs.commit }}
        tag: ${{ steps.data.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
